[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@primuslabs/zktls-contracts/=lib/zktls-contracts/",
    "@openzeppelin/=lib/zktls-contracts/lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
